# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        :title

# Setup
title:            Python Codelabs
tagline:          Snake charming, one step at a time. 
url:              http://jennielees.github.io/python-codelabs/
paginate:         1
baseurl:          http://jennielees.github.io/python-codelabs/
author:
  name:           Jennie Lees
  url:            https://twitter.com/jennielees
  email:          jennielees@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jennielees/python-codelabs
