# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
- jemoji

# Permalinks
permalink:        :title

# Setup
title:            Full-Stack Development
tagline:          Hackbright Part-Time Classes
url:              https://jennielees.github.io/full-stack/
paginate:         1
baseurl:          /full-stack
author:
  name:           Jennie Lees
  url:            https://twitter.com/jennielees
  email:          jennielees@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jennielees/python-codelabs
