# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        :title

# Setup
title:            Python Codelabs
tagline:          Hackbright Back-End Web Development
url:              labs.bewd.co
paginate:         1
baseurl:          
author:
  name:           Jennie Lees
  url:            https://twitter.com/jennielees
  email:          jennielees@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jennielees/python-codelabs
